#!/usr/bin/env python3
"""Copy data/valrose.geojson into src/04-campus-data.js, which is what the
game actually loads. Run this after build_campus.py. Kept separate so you can
hand-edit the GeoJSON (in the game's map mode, say) without rerunning the
whole pipeline."""
import json, os
root = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
gj = json.load(open(os.path.join(root, 'data', 'valrose.geojson')))
out = os.path.join(root, 'src', '04-campus-data.js')
open(out, 'w').write(
    "/* 04-campus-data.js — GENERATED by tools/embed_campus.py, do not hand-edit.\n\n"
    "   Parc Valrose from OpenStreetMap (ODbL) plus the circuit routed from the GPX\n"
    "   waypoints. Source of truth is data/valrose.geojson. */\n\n"
    "const CAMPUS = " + json.dumps(gj, separators=(',', ':')) + ";\n")
n = len(gj["features"])
print("embedded %d features (%d KB) into src/04-campus-data.js" % (n, os.path.getsize(out)//1024))
